FROM debian:buster

# Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update

RUN apt-get install -y sudo build-essential \
  autoconf libtool dh-make \
  vim

# NDK dependencies
RUN apt-get install -y \
  libprotobuf-dev libprotoc-dev \
  protobuf-compiler-grpc libgrpc++-dev libgrpc++1 \
  libyaml-cpp-dev \
  libudev-dev libcap-dev \
  python3 \
  python3-pip \
  cmake \
  ninja-build \
  git \
  libssl-dev \
  libc-ares-dev

# but we need gcc7
RUN apt-get -y install gcc-7 g++-7
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 7
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 7

RUN curl -o /tmp/nfpm.deb -L https://github.com/goreleaser/nfpm/releases/download/v2.6.0/nfpm_amd64.deb && dpkg -i /tmp/nfpm.deb && rm -f /tmp/nfpm.deb

RUN apt-get -y install python3-pip
RUN pip3 install grpcio==1.39.0 && pip3 install grpcio-tools==1.39.0

# fixup rootfs
RUN rm -f /bin/sh && ln -s bash /bin/sh
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# cleanup
RUN apt-get clean autoclean && \
  apt-get autoremove --yes && \
  rm -rf /var/lib/{cache,log}/
